customhost = "employee.cxdymafgd8jd.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "lowchoonkeat-employee"
customregion = "us-east-1"
